<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-UN73C2C" failures="1" tests="3" name="ErrorValidationsTest" time="61.047" errors="0" timestamp="2025-10-06T16:02:19 IST">
  <testcase classname="taransinghlearning.Tests.ErrorValidationsTest" name="loginErrorValidation" time="0.62"/>
  <testcase classname="taransinghlearning.Tests.ErrorValidationsTest" name="productErrorValidation" time="0.655">
    <skipped/>
  </testcase> <!-- productErrorValidation -->
  <testcase classname="taransinghlearning.Tests.ErrorValidationsTest" name="productErrorValidation" time="32.743">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at taransinghlearning.Tests.ErrorValidationsTest.productErrorValidation(ErrorValidationsTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- ErrorValidationsTest -->
